name: customer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.0.4
  path: ^1.9.1
  file_picker: ^10.3.6
  url_launcher: ^6.1.11
  permission_handler: ^12.0.1
  flutter_svg: ^2.0.9
  fl_chart: ^1.1.1
  # data_table_2: 2.6.0
  syncfusion_flutter_charts: ^31.2.5
  syncfusion_flutter_datagrid: ^31.2.5
  flutter_local_notifications: ^19.5.0
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0
  flutter_typeahead: ^5.2.0
  intl_phone_number_input: ^0.7.5
  flutter_rating_bar: ^4.0.1
  geolocator: ^14.0.2
  web_socket_channel: ^3.0.0
  socket_io_client: ^3.1.2
  path_provider: ^2.1.1
  open_file: ^3.3.3
  pdf: ^3.10.4
  printing: ^5.11.1
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^10.0.0-beta.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  get_it: ^9.0.5
  dio: ^5.3.2
  logger: ^2.6.2
  dartz: ^0.10.1
  syncfusion_flutter_gauges: ^31.2.5
  saudi_riyal_symbol: ^0.0.7
  flutter_launcher_icons: ^0.14.4
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^3.1.0
  geocoding: ^4.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  flutter_hooks: ^0.21.3+1
  shimmer: ^3.0.0
  glass: ^2.0.0+2
  lottie: ^3.3.2
  get_storage: ^2.1.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.10.6
  webview_flutter_wkwebview: ^3.9.4
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  country_picker: ^2.0.23
  video_player: ^2.8.2
  chewie: ^1.7.2
  rename: ^3.1.0
  audioplayers: ^6.1.0
  phone_otp_verification: 1.0.3
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_bloc: ^9.1.1
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  flutter_intl_phone_field: ^0.0.7
  dashed_border: 1.0.2
  cloud_firestore: ^6.1.0
  widget_to_marker: ^1.0.6
  change_app_package_name: ^1.1.0
  country_code_picker: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_stripe: 12.1.1
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon-01.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/logo.mp4


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo_regular.ttf
        - asset: assets/fonts/cairo_bold.ttf
          weight: 700
